FROM docker.io/prom/prometheus:v3.2.1@sha256:6927e0919a144aa7616fd0137d4816816d42f6b816de3af269ab065250859a62

USER nobody

# data from ~ 2025-05-26 11:00 to 2025-05-26 12:05
COPY e2e/provisioning/prometheus/data.zip /prometheus/data.zip
RUN unzip /prometheus/data.zip 
RUN rm /prometheus/data.zip 

COPY e2e/provisioning/prometheus/prometheus.yml /etc/prometheus/prometheus.yml
