name: Version Bump & Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Semver type of new version (major / minor / patch)'
        required: true
        type: choice
        options:
          - patch
          - minor
          - major
      generate-changelog:
        description: 'Generate changelog'
        required: false
        type: boolean
        default: true

jobs:
  bump-version:
    # Don't run on forks
    if: github.repository == 'grafana/traces-drilldown'
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Version bump
        uses: grafana/plugin-ci-workflows/actions/plugins/version-bump-changelog@main # zizmor: ignore[unpinned-uses]
        with:
          generate-changelog: ${{ inputs.generate-changelog }}
          version: ${{ inputs.version }}
  CD:
    name: Deploy plugin
    needs: bump-version
    uses: grafana/plugin-ci-workflows/.github/workflows/cd.yml@main
    permissions:
      contents: write
      id-token: write
      attestations: write
    with:
      environment: prod
      attestation: true
      grafana-cloud-deployment-type: provisioned
      auto-merge-environments: dev,ops

      argo-workflow-slack-channel: '#proj-tracesdrilldown-cd'

      # Playwright
      run-playwright: false
      run-playwright-docker: false
      upload-playwright-artifacts: true # IMPORTANT: we must ensure there are no unmasked secrets in the E2E tests
      run-playwright-with-skip-grafana-dev-image: true
      playwright-report-path: e2e/test-reports/
      playwright-docker-compose-file: docker-compose.yaml
      playwright-grafana-url: http://localhost:3001
