name: Swift Package CI

permissions: {}

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - name: Set up Swift
        uses: maxim-lobanov/setup-xcode@60606e260d2fc5762a71e64e74b2174e8ea3c8bd # v1.6.0
        with:
          xcode-version: latest

      - name: Install Linters/Formatters
        run: brew install swiftlint swiftformat

      - name: Check Formatting
        run: swiftformat . --lint

      - name: Run Linter
        run: swiftlint lint --strict # --strict makes warnings fail the build

      - name: Build Swift package
        run: swift build

      - name: Run tests
        run: swift test
