/*
Asserts, Inc

Asserts Public API

API version: 2025.11.24-113232
Contact: support@asserts.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gcom

import (
	"encoding/json"
)

// checks if the CustomKpiDashConfigDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CustomKpiDashConfigDto{}

// CustomKpiDashConfigDto struct for CustomKpiDashConfigDto
type CustomKpiDashConfigDto struct {
	KpiDashConfigs       []CustomDashConfigsDto `json:"kpiDashConfigs,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _CustomKpiDashConfigDto CustomKpiDashConfigDto

// NewCustomKpiDashConfigDto instantiates a new CustomKpiDashConfigDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCustomKpiDashConfigDto() *CustomKpiDashConfigDto {
	this := CustomKpiDashConfigDto{}
	return &this
}

// NewCustomKpiDashConfigDtoWithDefaults instantiates a new CustomKpiDashConfigDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCustomKpiDashConfigDtoWithDefaults() *CustomKpiDashConfigDto {
	this := CustomKpiDashConfigDto{}
	return &this
}

// GetKpiDashConfigs returns the KpiDashConfigs field value if set, zero value otherwise.
func (o *CustomKpiDashConfigDto) GetKpiDashConfigs() []CustomDashConfigsDto {
	if o == nil || IsNil(o.KpiDashConfigs) {
		var ret []CustomDashConfigsDto
		return ret
	}
	return o.KpiDashConfigs
}

// GetKpiDashConfigsOk returns a tuple with the KpiDashConfigs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomKpiDashConfigDto) GetKpiDashConfigsOk() ([]CustomDashConfigsDto, bool) {
	if o == nil || IsNil(o.KpiDashConfigs) {
		return nil, false
	}
	return o.KpiDashConfigs, true
}

// HasKpiDashConfigs returns a boolean if a field has been set.
func (o *CustomKpiDashConfigDto) HasKpiDashConfigs() bool {
	if o != nil && !IsNil(o.KpiDashConfigs) {
		return true
	}

	return false
}

// SetKpiDashConfigs gets a reference to the given []CustomDashConfigsDto and assigns it to the KpiDashConfigs field.
func (o *CustomKpiDashConfigDto) SetKpiDashConfigs(v []CustomDashConfigsDto) {
	o.KpiDashConfigs = v
}

func (o CustomKpiDashConfigDto) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CustomKpiDashConfigDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.KpiDashConfigs) {
		toSerialize["kpiDashConfigs"] = o.KpiDashConfigs
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CustomKpiDashConfigDto) UnmarshalJSON(data []byte) (err error) {
	varCustomKpiDashConfigDto := _CustomKpiDashConfigDto{}

	err = json.Unmarshal(data, &varCustomKpiDashConfigDto)

	if err != nil {
		return err
	}

	*o = CustomKpiDashConfigDto(varCustomKpiDashConfigDto)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "kpiDashConfigs")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCustomKpiDashConfigDto struct {
	value *CustomKpiDashConfigDto
	isSet bool
}

func (v NullableCustomKpiDashConfigDto) Get() *CustomKpiDashConfigDto {
	return v.value
}

func (v *NullableCustomKpiDashConfigDto) Set(val *CustomKpiDashConfigDto) {
	v.value = val
	v.isSet = true
}

func (v NullableCustomKpiDashConfigDto) IsSet() bool {
	return v.isSet
}

func (v *NullableCustomKpiDashConfigDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCustomKpiDashConfigDto(val *CustomKpiDashConfigDto) *NullableCustomKpiDashConfigDto {
	return &NullableCustomKpiDashConfigDto{value: val, isSet: true}
}

func (v NullableCustomKpiDashConfigDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCustomKpiDashConfigDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
