/*
Asserts, Inc

Asserts Public API

API version: 2025.11.24-113232
Contact: support@asserts.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gcom

import (
	"encoding/json"
)

// checks if the PrometheusRuleAnnotations type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PrometheusRuleAnnotations{}

// PrometheusRuleAnnotations struct for PrometheusRuleAnnotations
type PrometheusRuleAnnotations struct {
	Empty                *bool `json:"empty,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _PrometheusRuleAnnotations PrometheusRuleAnnotations

// NewPrometheusRuleAnnotations instantiates a new PrometheusRuleAnnotations object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPrometheusRuleAnnotations() *PrometheusRuleAnnotations {
	this := PrometheusRuleAnnotations{}
	return &this
}

// NewPrometheusRuleAnnotationsWithDefaults instantiates a new PrometheusRuleAnnotations object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPrometheusRuleAnnotationsWithDefaults() *PrometheusRuleAnnotations {
	this := PrometheusRuleAnnotations{}
	return &this
}

// GetEmpty returns the Empty field value if set, zero value otherwise.
func (o *PrometheusRuleAnnotations) GetEmpty() bool {
	if o == nil || IsNil(o.Empty) {
		var ret bool
		return ret
	}
	return *o.Empty
}

// GetEmptyOk returns a tuple with the Empty field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PrometheusRuleAnnotations) GetEmptyOk() (*bool, bool) {
	if o == nil || IsNil(o.Empty) {
		return nil, false
	}
	return o.Empty, true
}

// HasEmpty returns a boolean if a field has been set.
func (o *PrometheusRuleAnnotations) HasEmpty() bool {
	if o != nil && !IsNil(o.Empty) {
		return true
	}

	return false
}

// SetEmpty gets a reference to the given bool and assigns it to the Empty field.
func (o *PrometheusRuleAnnotations) SetEmpty(v bool) {
	o.Empty = &v
}

func (o PrometheusRuleAnnotations) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PrometheusRuleAnnotations) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Empty) {
		toSerialize["empty"] = o.Empty
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *PrometheusRuleAnnotations) UnmarshalJSON(data []byte) (err error) {
	varPrometheusRuleAnnotations := _PrometheusRuleAnnotations{}

	err = json.Unmarshal(data, &varPrometheusRuleAnnotations)

	if err != nil {
		return err
	}

	*o = PrometheusRuleAnnotations(varPrometheusRuleAnnotations)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "empty")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullablePrometheusRuleAnnotations struct {
	value *PrometheusRuleAnnotations
	isSet bool
}

func (v NullablePrometheusRuleAnnotations) Get() *PrometheusRuleAnnotations {
	return v.value
}

func (v *NullablePrometheusRuleAnnotations) Set(val *PrometheusRuleAnnotations) {
	v.value = val
	v.isSet = true
}

func (v NullablePrometheusRuleAnnotations) IsSet() bool {
	return v.isSet
}

func (v *NullablePrometheusRuleAnnotations) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePrometheusRuleAnnotations(val *PrometheusRuleAnnotations) *NullablePrometheusRuleAnnotations {
	return &NullablePrometheusRuleAnnotations{value: val, isSet: true}
}

func (v NullablePrometheusRuleAnnotations) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePrometheusRuleAnnotations) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
