/*
Asserts, Inc

Asserts Public API

API version: 2025.11.24-113232
Contact: support@asserts.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gcom

import (
	"encoding/json"
)

// checks if the HealthThresholdV2Dto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &HealthThresholdV2Dto{}

// HealthThresholdV2Dto struct for HealthThresholdV2Dto
type HealthThresholdV2Dto struct {
	AssertionName        *string `json:"assertionName,omitempty"`
	Expression           *string `json:"expression,omitempty"`
	AlertCategory        *string `json:"alertCategory,omitempty"`
	EntityType           *string `json:"entityType,omitempty"`
	ManagedBy            *string `json:"managedBy,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _HealthThresholdV2Dto HealthThresholdV2Dto

// NewHealthThresholdV2Dto instantiates a new HealthThresholdV2Dto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewHealthThresholdV2Dto() *HealthThresholdV2Dto {
	this := HealthThresholdV2Dto{}
	return &this
}

// NewHealthThresholdV2DtoWithDefaults instantiates a new HealthThresholdV2Dto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewHealthThresholdV2DtoWithDefaults() *HealthThresholdV2Dto {
	this := HealthThresholdV2Dto{}
	return &this
}

// GetAssertionName returns the AssertionName field value if set, zero value otherwise.
func (o *HealthThresholdV2Dto) GetAssertionName() string {
	if o == nil || IsNil(o.AssertionName) {
		var ret string
		return ret
	}
	return *o.AssertionName
}

// GetAssertionNameOk returns a tuple with the AssertionName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HealthThresholdV2Dto) GetAssertionNameOk() (*string, bool) {
	if o == nil || IsNil(o.AssertionName) {
		return nil, false
	}
	return o.AssertionName, true
}

// HasAssertionName returns a boolean if a field has been set.
func (o *HealthThresholdV2Dto) HasAssertionName() bool {
	if o != nil && !IsNil(o.AssertionName) {
		return true
	}

	return false
}

// SetAssertionName gets a reference to the given string and assigns it to the AssertionName field.
func (o *HealthThresholdV2Dto) SetAssertionName(v string) {
	o.AssertionName = &v
}

// GetExpression returns the Expression field value if set, zero value otherwise.
func (o *HealthThresholdV2Dto) GetExpression() string {
	if o == nil || IsNil(o.Expression) {
		var ret string
		return ret
	}
	return *o.Expression
}

// GetExpressionOk returns a tuple with the Expression field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HealthThresholdV2Dto) GetExpressionOk() (*string, bool) {
	if o == nil || IsNil(o.Expression) {
		return nil, false
	}
	return o.Expression, true
}

// HasExpression returns a boolean if a field has been set.
func (o *HealthThresholdV2Dto) HasExpression() bool {
	if o != nil && !IsNil(o.Expression) {
		return true
	}

	return false
}

// SetExpression gets a reference to the given string and assigns it to the Expression field.
func (o *HealthThresholdV2Dto) SetExpression(v string) {
	o.Expression = &v
}

// GetAlertCategory returns the AlertCategory field value if set, zero value otherwise.
func (o *HealthThresholdV2Dto) GetAlertCategory() string {
	if o == nil || IsNil(o.AlertCategory) {
		var ret string
		return ret
	}
	return *o.AlertCategory
}

// GetAlertCategoryOk returns a tuple with the AlertCategory field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HealthThresholdV2Dto) GetAlertCategoryOk() (*string, bool) {
	if o == nil || IsNil(o.AlertCategory) {
		return nil, false
	}
	return o.AlertCategory, true
}

// HasAlertCategory returns a boolean if a field has been set.
func (o *HealthThresholdV2Dto) HasAlertCategory() bool {
	if o != nil && !IsNil(o.AlertCategory) {
		return true
	}

	return false
}

// SetAlertCategory gets a reference to the given string and assigns it to the AlertCategory field.
func (o *HealthThresholdV2Dto) SetAlertCategory(v string) {
	o.AlertCategory = &v
}

// GetEntityType returns the EntityType field value if set, zero value otherwise.
func (o *HealthThresholdV2Dto) GetEntityType() string {
	if o == nil || IsNil(o.EntityType) {
		var ret string
		return ret
	}
	return *o.EntityType
}

// GetEntityTypeOk returns a tuple with the EntityType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HealthThresholdV2Dto) GetEntityTypeOk() (*string, bool) {
	if o == nil || IsNil(o.EntityType) {
		return nil, false
	}
	return o.EntityType, true
}

// HasEntityType returns a boolean if a field has been set.
func (o *HealthThresholdV2Dto) HasEntityType() bool {
	if o != nil && !IsNil(o.EntityType) {
		return true
	}

	return false
}

// SetEntityType gets a reference to the given string and assigns it to the EntityType field.
func (o *HealthThresholdV2Dto) SetEntityType(v string) {
	o.EntityType = &v
}

// GetManagedBy returns the ManagedBy field value if set, zero value otherwise.
func (o *HealthThresholdV2Dto) GetManagedBy() string {
	if o == nil || IsNil(o.ManagedBy) {
		var ret string
		return ret
	}
	return *o.ManagedBy
}

// GetManagedByOk returns a tuple with the ManagedBy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HealthThresholdV2Dto) GetManagedByOk() (*string, bool) {
	if o == nil || IsNil(o.ManagedBy) {
		return nil, false
	}
	return o.ManagedBy, true
}

// HasManagedBy returns a boolean if a field has been set.
func (o *HealthThresholdV2Dto) HasManagedBy() bool {
	if o != nil && !IsNil(o.ManagedBy) {
		return true
	}

	return false
}

// SetManagedBy gets a reference to the given string and assigns it to the ManagedBy field.
func (o *HealthThresholdV2Dto) SetManagedBy(v string) {
	o.ManagedBy = &v
}

func (o HealthThresholdV2Dto) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o HealthThresholdV2Dto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AssertionName) {
		toSerialize["assertionName"] = o.AssertionName
	}
	if !IsNil(o.Expression) {
		toSerialize["expression"] = o.Expression
	}
	if !IsNil(o.AlertCategory) {
		toSerialize["alertCategory"] = o.AlertCategory
	}
	if !IsNil(o.EntityType) {
		toSerialize["entityType"] = o.EntityType
	}
	if !IsNil(o.ManagedBy) {
		toSerialize["managedBy"] = o.ManagedBy
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *HealthThresholdV2Dto) UnmarshalJSON(data []byte) (err error) {
	varHealthThresholdV2Dto := _HealthThresholdV2Dto{}

	err = json.Unmarshal(data, &varHealthThresholdV2Dto)

	if err != nil {
		return err
	}

	*o = HealthThresholdV2Dto(varHealthThresholdV2Dto)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "assertionName")
		delete(additionalProperties, "expression")
		delete(additionalProperties, "alertCategory")
		delete(additionalProperties, "entityType")
		delete(additionalProperties, "managedBy")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableHealthThresholdV2Dto struct {
	value *HealthThresholdV2Dto
	isSet bool
}

func (v NullableHealthThresholdV2Dto) Get() *HealthThresholdV2Dto {
	return v.value
}

func (v *NullableHealthThresholdV2Dto) Set(val *HealthThresholdV2Dto) {
	v.value = val
	v.isSet = true
}

func (v NullableHealthThresholdV2Dto) IsSet() bool {
	return v.isSet
}

func (v *NullableHealthThresholdV2Dto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableHealthThresholdV2Dto(val *HealthThresholdV2Dto) *NullableHealthThresholdV2Dto {
	return &NullableHealthThresholdV2Dto{value: val, isSet: true}
}

func (v NullableHealthThresholdV2Dto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableHealthThresholdV2Dto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
