/*
Asserts, Inc

Asserts Public API

API version: 2025.11.24-113232
Contact: support@asserts.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gcom

import (
	"encoding/json"
)

// checks if the DefaultHttpStatusCode type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DefaultHttpStatusCode{}

// DefaultHttpStatusCode struct for DefaultHttpStatusCode
type DefaultHttpStatusCode struct {
	Error                *bool `json:"error,omitempty"`
	Is5xxServerError     *bool `json:"is5xxServerError,omitempty"`
	Is2xxSuccessful      *bool `json:"is2xxSuccessful,omitempty"`
	Is4xxClientError     *bool `json:"is4xxClientError,omitempty"`
	Is1xxInformational   *bool `json:"is1xxInformational,omitempty"`
	Is3xxRedirection     *bool `json:"is3xxRedirection,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _DefaultHttpStatusCode DefaultHttpStatusCode

// NewDefaultHttpStatusCode instantiates a new DefaultHttpStatusCode object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDefaultHttpStatusCode() *DefaultHttpStatusCode {
	this := DefaultHttpStatusCode{}
	return &this
}

// NewDefaultHttpStatusCodeWithDefaults instantiates a new DefaultHttpStatusCode object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDefaultHttpStatusCodeWithDefaults() *DefaultHttpStatusCode {
	this := DefaultHttpStatusCode{}
	return &this
}

// GetError returns the Error field value if set, zero value otherwise.
func (o *DefaultHttpStatusCode) GetError() bool {
	if o == nil || IsNil(o.Error) {
		var ret bool
		return ret
	}
	return *o.Error
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DefaultHttpStatusCode) GetErrorOk() (*bool, bool) {
	if o == nil || IsNil(o.Error) {
		return nil, false
	}
	return o.Error, true
}

// HasError returns a boolean if a field has been set.
func (o *DefaultHttpStatusCode) HasError() bool {
	if o != nil && !IsNil(o.Error) {
		return true
	}

	return false
}

// SetError gets a reference to the given bool and assigns it to the Error field.
func (o *DefaultHttpStatusCode) SetError(v bool) {
	o.Error = &v
}

// GetIs5xxServerError returns the Is5xxServerError field value if set, zero value otherwise.
func (o *DefaultHttpStatusCode) GetIs5xxServerError() bool {
	if o == nil || IsNil(o.Is5xxServerError) {
		var ret bool
		return ret
	}
	return *o.Is5xxServerError
}

// GetIs5xxServerErrorOk returns a tuple with the Is5xxServerError field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DefaultHttpStatusCode) GetIs5xxServerErrorOk() (*bool, bool) {
	if o == nil || IsNil(o.Is5xxServerError) {
		return nil, false
	}
	return o.Is5xxServerError, true
}

// HasIs5xxServerError returns a boolean if a field has been set.
func (o *DefaultHttpStatusCode) HasIs5xxServerError() bool {
	if o != nil && !IsNil(o.Is5xxServerError) {
		return true
	}

	return false
}

// SetIs5xxServerError gets a reference to the given bool and assigns it to the Is5xxServerError field.
func (o *DefaultHttpStatusCode) SetIs5xxServerError(v bool) {
	o.Is5xxServerError = &v
}

// GetIs2xxSuccessful returns the Is2xxSuccessful field value if set, zero value otherwise.
func (o *DefaultHttpStatusCode) GetIs2xxSuccessful() bool {
	if o == nil || IsNil(o.Is2xxSuccessful) {
		var ret bool
		return ret
	}
	return *o.Is2xxSuccessful
}

// GetIs2xxSuccessfulOk returns a tuple with the Is2xxSuccessful field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DefaultHttpStatusCode) GetIs2xxSuccessfulOk() (*bool, bool) {
	if o == nil || IsNil(o.Is2xxSuccessful) {
		return nil, false
	}
	return o.Is2xxSuccessful, true
}

// HasIs2xxSuccessful returns a boolean if a field has been set.
func (o *DefaultHttpStatusCode) HasIs2xxSuccessful() bool {
	if o != nil && !IsNil(o.Is2xxSuccessful) {
		return true
	}

	return false
}

// SetIs2xxSuccessful gets a reference to the given bool and assigns it to the Is2xxSuccessful field.
func (o *DefaultHttpStatusCode) SetIs2xxSuccessful(v bool) {
	o.Is2xxSuccessful = &v
}

// GetIs4xxClientError returns the Is4xxClientError field value if set, zero value otherwise.
func (o *DefaultHttpStatusCode) GetIs4xxClientError() bool {
	if o == nil || IsNil(o.Is4xxClientError) {
		var ret bool
		return ret
	}
	return *o.Is4xxClientError
}

// GetIs4xxClientErrorOk returns a tuple with the Is4xxClientError field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DefaultHttpStatusCode) GetIs4xxClientErrorOk() (*bool, bool) {
	if o == nil || IsNil(o.Is4xxClientError) {
		return nil, false
	}
	return o.Is4xxClientError, true
}

// HasIs4xxClientError returns a boolean if a field has been set.
func (o *DefaultHttpStatusCode) HasIs4xxClientError() bool {
	if o != nil && !IsNil(o.Is4xxClientError) {
		return true
	}

	return false
}

// SetIs4xxClientError gets a reference to the given bool and assigns it to the Is4xxClientError field.
func (o *DefaultHttpStatusCode) SetIs4xxClientError(v bool) {
	o.Is4xxClientError = &v
}

// GetIs1xxInformational returns the Is1xxInformational field value if set, zero value otherwise.
func (o *DefaultHttpStatusCode) GetIs1xxInformational() bool {
	if o == nil || IsNil(o.Is1xxInformational) {
		var ret bool
		return ret
	}
	return *o.Is1xxInformational
}

// GetIs1xxInformationalOk returns a tuple with the Is1xxInformational field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DefaultHttpStatusCode) GetIs1xxInformationalOk() (*bool, bool) {
	if o == nil || IsNil(o.Is1xxInformational) {
		return nil, false
	}
	return o.Is1xxInformational, true
}

// HasIs1xxInformational returns a boolean if a field has been set.
func (o *DefaultHttpStatusCode) HasIs1xxInformational() bool {
	if o != nil && !IsNil(o.Is1xxInformational) {
		return true
	}

	return false
}

// SetIs1xxInformational gets a reference to the given bool and assigns it to the Is1xxInformational field.
func (o *DefaultHttpStatusCode) SetIs1xxInformational(v bool) {
	o.Is1xxInformational = &v
}

// GetIs3xxRedirection returns the Is3xxRedirection field value if set, zero value otherwise.
func (o *DefaultHttpStatusCode) GetIs3xxRedirection() bool {
	if o == nil || IsNil(o.Is3xxRedirection) {
		var ret bool
		return ret
	}
	return *o.Is3xxRedirection
}

// GetIs3xxRedirectionOk returns a tuple with the Is3xxRedirection field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DefaultHttpStatusCode) GetIs3xxRedirectionOk() (*bool, bool) {
	if o == nil || IsNil(o.Is3xxRedirection) {
		return nil, false
	}
	return o.Is3xxRedirection, true
}

// HasIs3xxRedirection returns a boolean if a field has been set.
func (o *DefaultHttpStatusCode) HasIs3xxRedirection() bool {
	if o != nil && !IsNil(o.Is3xxRedirection) {
		return true
	}

	return false
}

// SetIs3xxRedirection gets a reference to the given bool and assigns it to the Is3xxRedirection field.
func (o *DefaultHttpStatusCode) SetIs3xxRedirection(v bool) {
	o.Is3xxRedirection = &v
}

func (o DefaultHttpStatusCode) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DefaultHttpStatusCode) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Error) {
		toSerialize["error"] = o.Error
	}
	if !IsNil(o.Is5xxServerError) {
		toSerialize["is5xxServerError"] = o.Is5xxServerError
	}
	if !IsNil(o.Is2xxSuccessful) {
		toSerialize["is2xxSuccessful"] = o.Is2xxSuccessful
	}
	if !IsNil(o.Is4xxClientError) {
		toSerialize["is4xxClientError"] = o.Is4xxClientError
	}
	if !IsNil(o.Is1xxInformational) {
		toSerialize["is1xxInformational"] = o.Is1xxInformational
	}
	if !IsNil(o.Is3xxRedirection) {
		toSerialize["is3xxRedirection"] = o.Is3xxRedirection
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *DefaultHttpStatusCode) UnmarshalJSON(data []byte) (err error) {
	varDefaultHttpStatusCode := _DefaultHttpStatusCode{}

	err = json.Unmarshal(data, &varDefaultHttpStatusCode)

	if err != nil {
		return err
	}

	*o = DefaultHttpStatusCode(varDefaultHttpStatusCode)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "error")
		delete(additionalProperties, "is5xxServerError")
		delete(additionalProperties, "is2xxSuccessful")
		delete(additionalProperties, "is4xxClientError")
		delete(additionalProperties, "is1xxInformational")
		delete(additionalProperties, "is3xxRedirection")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableDefaultHttpStatusCode struct {
	value *DefaultHttpStatusCode
	isSet bool
}

func (v NullableDefaultHttpStatusCode) Get() *DefaultHttpStatusCode {
	return v.value
}

func (v *NullableDefaultHttpStatusCode) Set(val *DefaultHttpStatusCode) {
	v.value = val
	v.isSet = true
}

func (v NullableDefaultHttpStatusCode) IsSet() bool {
	return v.isSet
}

func (v *NullableDefaultHttpStatusCode) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDefaultHttpStatusCode(val *DefaultHttpStatusCode) *NullableDefaultHttpStatusCode {
	return &NullableDefaultHttpStatusCode{value: val, isSet: true}
}

func (v NullableDefaultHttpStatusCode) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDefaultHttpStatusCode) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
