/*
Asserts, Inc

Asserts Public API

API version: 2025.11.24-113232
Contact: support@asserts.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gcom

import (
	"encoding/json"
)

// checks if the AssertionSearchRequestDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AssertionSearchRequestDto{}

// AssertionSearchRequestDto struct for AssertionSearchRequestDto
type AssertionSearchRequestDto struct {
	DefinitionId                                  *int32             `json:"definitionId,omitempty"`
	TimeCriteria                                  *TimeCriteriaDto   `json:"timeCriteria,omitempty"`
	ScopeCriteria                                 *ScopeCriteriaDto  `json:"scopeCriteria,omitempty"`
	PageNum                                       *int32             `json:"pageNum,omitempty"`
	Bindings                                      map[string]string  `json:"bindings,omitempty"`
	FilterCriteria                                []EntityMatcherDto `json:"filterCriteria,omitempty"`
	HideAssertionsOlderThanNHours                 *int32             `json:"hideAssertionsOlderThanNHours,omitempty"`
	AlertCategories                               []string           `json:"alertCategories,omitempty"`
	Query                                         *string            `json:"query,omitempty"`
	CurrentWBEntityCount                          *int32             `json:"currentWBEntityCount,omitempty"`
	HideAssertionsPresentMoreThanPercentageOfTime *int32             `json:"hideAssertionsPresentMoreThanPercentageOfTime,omitempty"`
	AdditionalProperties                          map[string]interface{}
}

type _AssertionSearchRequestDto AssertionSearchRequestDto

// NewAssertionSearchRequestDto instantiates a new AssertionSearchRequestDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAssertionSearchRequestDto() *AssertionSearchRequestDto {
	this := AssertionSearchRequestDto{}
	return &this
}

// NewAssertionSearchRequestDtoWithDefaults instantiates a new AssertionSearchRequestDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAssertionSearchRequestDtoWithDefaults() *AssertionSearchRequestDto {
	this := AssertionSearchRequestDto{}
	return &this
}

// GetDefinitionId returns the DefinitionId field value if set, zero value otherwise.
func (o *AssertionSearchRequestDto) GetDefinitionId() int32 {
	if o == nil || IsNil(o.DefinitionId) {
		var ret int32
		return ret
	}
	return *o.DefinitionId
}

// GetDefinitionIdOk returns a tuple with the DefinitionId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssertionSearchRequestDto) GetDefinitionIdOk() (*int32, bool) {
	if o == nil || IsNil(o.DefinitionId) {
		return nil, false
	}
	return o.DefinitionId, true
}

// HasDefinitionId returns a boolean if a field has been set.
func (o *AssertionSearchRequestDto) HasDefinitionId() bool {
	if o != nil && !IsNil(o.DefinitionId) {
		return true
	}

	return false
}

// SetDefinitionId gets a reference to the given int32 and assigns it to the DefinitionId field.
func (o *AssertionSearchRequestDto) SetDefinitionId(v int32) {
	o.DefinitionId = &v
}

// GetTimeCriteria returns the TimeCriteria field value if set, zero value otherwise.
func (o *AssertionSearchRequestDto) GetTimeCriteria() TimeCriteriaDto {
	if o == nil || IsNil(o.TimeCriteria) {
		var ret TimeCriteriaDto
		return ret
	}
	return *o.TimeCriteria
}

// GetTimeCriteriaOk returns a tuple with the TimeCriteria field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssertionSearchRequestDto) GetTimeCriteriaOk() (*TimeCriteriaDto, bool) {
	if o == nil || IsNil(o.TimeCriteria) {
		return nil, false
	}
	return o.TimeCriteria, true
}

// HasTimeCriteria returns a boolean if a field has been set.
func (o *AssertionSearchRequestDto) HasTimeCriteria() bool {
	if o != nil && !IsNil(o.TimeCriteria) {
		return true
	}

	return false
}

// SetTimeCriteria gets a reference to the given TimeCriteriaDto and assigns it to the TimeCriteria field.
func (o *AssertionSearchRequestDto) SetTimeCriteria(v TimeCriteriaDto) {
	o.TimeCriteria = &v
}

// GetScopeCriteria returns the ScopeCriteria field value if set, zero value otherwise.
func (o *AssertionSearchRequestDto) GetScopeCriteria() ScopeCriteriaDto {
	if o == nil || IsNil(o.ScopeCriteria) {
		var ret ScopeCriteriaDto
		return ret
	}
	return *o.ScopeCriteria
}

// GetScopeCriteriaOk returns a tuple with the ScopeCriteria field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssertionSearchRequestDto) GetScopeCriteriaOk() (*ScopeCriteriaDto, bool) {
	if o == nil || IsNil(o.ScopeCriteria) {
		return nil, false
	}
	return o.ScopeCriteria, true
}

// HasScopeCriteria returns a boolean if a field has been set.
func (o *AssertionSearchRequestDto) HasScopeCriteria() bool {
	if o != nil && !IsNil(o.ScopeCriteria) {
		return true
	}

	return false
}

// SetScopeCriteria gets a reference to the given ScopeCriteriaDto and assigns it to the ScopeCriteria field.
func (o *AssertionSearchRequestDto) SetScopeCriteria(v ScopeCriteriaDto) {
	o.ScopeCriteria = &v
}

// GetPageNum returns the PageNum field value if set, zero value otherwise.
func (o *AssertionSearchRequestDto) GetPageNum() int32 {
	if o == nil || IsNil(o.PageNum) {
		var ret int32
		return ret
	}
	return *o.PageNum
}

// GetPageNumOk returns a tuple with the PageNum field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssertionSearchRequestDto) GetPageNumOk() (*int32, bool) {
	if o == nil || IsNil(o.PageNum) {
		return nil, false
	}
	return o.PageNum, true
}

// HasPageNum returns a boolean if a field has been set.
func (o *AssertionSearchRequestDto) HasPageNum() bool {
	if o != nil && !IsNil(o.PageNum) {
		return true
	}

	return false
}

// SetPageNum gets a reference to the given int32 and assigns it to the PageNum field.
func (o *AssertionSearchRequestDto) SetPageNum(v int32) {
	o.PageNum = &v
}

// GetBindings returns the Bindings field value if set, zero value otherwise.
func (o *AssertionSearchRequestDto) GetBindings() map[string]string {
	if o == nil || IsNil(o.Bindings) {
		var ret map[string]string
		return ret
	}
	return o.Bindings
}

// GetBindingsOk returns a tuple with the Bindings field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssertionSearchRequestDto) GetBindingsOk() (map[string]string, bool) {
	if o == nil || IsNil(o.Bindings) {
		return map[string]string{}, false
	}
	return o.Bindings, true
}

// HasBindings returns a boolean if a field has been set.
func (o *AssertionSearchRequestDto) HasBindings() bool {
	if o != nil && !IsNil(o.Bindings) {
		return true
	}

	return false
}

// SetBindings gets a reference to the given map[string]string and assigns it to the Bindings field.
func (o *AssertionSearchRequestDto) SetBindings(v map[string]string) {
	o.Bindings = v
}

// GetFilterCriteria returns the FilterCriteria field value if set, zero value otherwise.
func (o *AssertionSearchRequestDto) GetFilterCriteria() []EntityMatcherDto {
	if o == nil || IsNil(o.FilterCriteria) {
		var ret []EntityMatcherDto
		return ret
	}
	return o.FilterCriteria
}

// GetFilterCriteriaOk returns a tuple with the FilterCriteria field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssertionSearchRequestDto) GetFilterCriteriaOk() ([]EntityMatcherDto, bool) {
	if o == nil || IsNil(o.FilterCriteria) {
		return nil, false
	}
	return o.FilterCriteria, true
}

// HasFilterCriteria returns a boolean if a field has been set.
func (o *AssertionSearchRequestDto) HasFilterCriteria() bool {
	if o != nil && !IsNil(o.FilterCriteria) {
		return true
	}

	return false
}

// SetFilterCriteria gets a reference to the given []EntityMatcherDto and assigns it to the FilterCriteria field.
func (o *AssertionSearchRequestDto) SetFilterCriteria(v []EntityMatcherDto) {
	o.FilterCriteria = v
}

// GetHideAssertionsOlderThanNHours returns the HideAssertionsOlderThanNHours field value if set, zero value otherwise.
func (o *AssertionSearchRequestDto) GetHideAssertionsOlderThanNHours() int32 {
	if o == nil || IsNil(o.HideAssertionsOlderThanNHours) {
		var ret int32
		return ret
	}
	return *o.HideAssertionsOlderThanNHours
}

// GetHideAssertionsOlderThanNHoursOk returns a tuple with the HideAssertionsOlderThanNHours field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssertionSearchRequestDto) GetHideAssertionsOlderThanNHoursOk() (*int32, bool) {
	if o == nil || IsNil(o.HideAssertionsOlderThanNHours) {
		return nil, false
	}
	return o.HideAssertionsOlderThanNHours, true
}

// HasHideAssertionsOlderThanNHours returns a boolean if a field has been set.
func (o *AssertionSearchRequestDto) HasHideAssertionsOlderThanNHours() bool {
	if o != nil && !IsNil(o.HideAssertionsOlderThanNHours) {
		return true
	}

	return false
}

// SetHideAssertionsOlderThanNHours gets a reference to the given int32 and assigns it to the HideAssertionsOlderThanNHours field.
func (o *AssertionSearchRequestDto) SetHideAssertionsOlderThanNHours(v int32) {
	o.HideAssertionsOlderThanNHours = &v
}

// GetAlertCategories returns the AlertCategories field value if set, zero value otherwise.
func (o *AssertionSearchRequestDto) GetAlertCategories() []string {
	if o == nil || IsNil(o.AlertCategories) {
		var ret []string
		return ret
	}
	return o.AlertCategories
}

// GetAlertCategoriesOk returns a tuple with the AlertCategories field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssertionSearchRequestDto) GetAlertCategoriesOk() ([]string, bool) {
	if o == nil || IsNil(o.AlertCategories) {
		return nil, false
	}
	return o.AlertCategories, true
}

// HasAlertCategories returns a boolean if a field has been set.
func (o *AssertionSearchRequestDto) HasAlertCategories() bool {
	if o != nil && !IsNil(o.AlertCategories) {
		return true
	}

	return false
}

// SetAlertCategories gets a reference to the given []string and assigns it to the AlertCategories field.
func (o *AssertionSearchRequestDto) SetAlertCategories(v []string) {
	o.AlertCategories = v
}

// GetQuery returns the Query field value if set, zero value otherwise.
func (o *AssertionSearchRequestDto) GetQuery() string {
	if o == nil || IsNil(o.Query) {
		var ret string
		return ret
	}
	return *o.Query
}

// GetQueryOk returns a tuple with the Query field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssertionSearchRequestDto) GetQueryOk() (*string, bool) {
	if o == nil || IsNil(o.Query) {
		return nil, false
	}
	return o.Query, true
}

// HasQuery returns a boolean if a field has been set.
func (o *AssertionSearchRequestDto) HasQuery() bool {
	if o != nil && !IsNil(o.Query) {
		return true
	}

	return false
}

// SetQuery gets a reference to the given string and assigns it to the Query field.
func (o *AssertionSearchRequestDto) SetQuery(v string) {
	o.Query = &v
}

// GetCurrentWBEntityCount returns the CurrentWBEntityCount field value if set, zero value otherwise.
func (o *AssertionSearchRequestDto) GetCurrentWBEntityCount() int32 {
	if o == nil || IsNil(o.CurrentWBEntityCount) {
		var ret int32
		return ret
	}
	return *o.CurrentWBEntityCount
}

// GetCurrentWBEntityCountOk returns a tuple with the CurrentWBEntityCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssertionSearchRequestDto) GetCurrentWBEntityCountOk() (*int32, bool) {
	if o == nil || IsNil(o.CurrentWBEntityCount) {
		return nil, false
	}
	return o.CurrentWBEntityCount, true
}

// HasCurrentWBEntityCount returns a boolean if a field has been set.
func (o *AssertionSearchRequestDto) HasCurrentWBEntityCount() bool {
	if o != nil && !IsNil(o.CurrentWBEntityCount) {
		return true
	}

	return false
}

// SetCurrentWBEntityCount gets a reference to the given int32 and assigns it to the CurrentWBEntityCount field.
func (o *AssertionSearchRequestDto) SetCurrentWBEntityCount(v int32) {
	o.CurrentWBEntityCount = &v
}

// GetHideAssertionsPresentMoreThanPercentageOfTime returns the HideAssertionsPresentMoreThanPercentageOfTime field value if set, zero value otherwise.
func (o *AssertionSearchRequestDto) GetHideAssertionsPresentMoreThanPercentageOfTime() int32 {
	if o == nil || IsNil(o.HideAssertionsPresentMoreThanPercentageOfTime) {
		var ret int32
		return ret
	}
	return *o.HideAssertionsPresentMoreThanPercentageOfTime
}

// GetHideAssertionsPresentMoreThanPercentageOfTimeOk returns a tuple with the HideAssertionsPresentMoreThanPercentageOfTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssertionSearchRequestDto) GetHideAssertionsPresentMoreThanPercentageOfTimeOk() (*int32, bool) {
	if o == nil || IsNil(o.HideAssertionsPresentMoreThanPercentageOfTime) {
		return nil, false
	}
	return o.HideAssertionsPresentMoreThanPercentageOfTime, true
}

// HasHideAssertionsPresentMoreThanPercentageOfTime returns a boolean if a field has been set.
func (o *AssertionSearchRequestDto) HasHideAssertionsPresentMoreThanPercentageOfTime() bool {
	if o != nil && !IsNil(o.HideAssertionsPresentMoreThanPercentageOfTime) {
		return true
	}

	return false
}

// SetHideAssertionsPresentMoreThanPercentageOfTime gets a reference to the given int32 and assigns it to the HideAssertionsPresentMoreThanPercentageOfTime field.
func (o *AssertionSearchRequestDto) SetHideAssertionsPresentMoreThanPercentageOfTime(v int32) {
	o.HideAssertionsPresentMoreThanPercentageOfTime = &v
}

func (o AssertionSearchRequestDto) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AssertionSearchRequestDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.DefinitionId) {
		toSerialize["definitionId"] = o.DefinitionId
	}
	if !IsNil(o.TimeCriteria) {
		toSerialize["timeCriteria"] = o.TimeCriteria
	}
	if !IsNil(o.ScopeCriteria) {
		toSerialize["scopeCriteria"] = o.ScopeCriteria
	}
	if !IsNil(o.PageNum) {
		toSerialize["pageNum"] = o.PageNum
	}
	if !IsNil(o.Bindings) {
		toSerialize["bindings"] = o.Bindings
	}
	if !IsNil(o.FilterCriteria) {
		toSerialize["filterCriteria"] = o.FilterCriteria
	}
	if !IsNil(o.HideAssertionsOlderThanNHours) {
		toSerialize["hideAssertionsOlderThanNHours"] = o.HideAssertionsOlderThanNHours
	}
	if !IsNil(o.AlertCategories) {
		toSerialize["alertCategories"] = o.AlertCategories
	}
	if !IsNil(o.Query) {
		toSerialize["query"] = o.Query
	}
	if !IsNil(o.CurrentWBEntityCount) {
		toSerialize["currentWBEntityCount"] = o.CurrentWBEntityCount
	}
	if !IsNil(o.HideAssertionsPresentMoreThanPercentageOfTime) {
		toSerialize["hideAssertionsPresentMoreThanPercentageOfTime"] = o.HideAssertionsPresentMoreThanPercentageOfTime
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *AssertionSearchRequestDto) UnmarshalJSON(data []byte) (err error) {
	varAssertionSearchRequestDto := _AssertionSearchRequestDto{}

	err = json.Unmarshal(data, &varAssertionSearchRequestDto)

	if err != nil {
		return err
	}

	*o = AssertionSearchRequestDto(varAssertionSearchRequestDto)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "definitionId")
		delete(additionalProperties, "timeCriteria")
		delete(additionalProperties, "scopeCriteria")
		delete(additionalProperties, "pageNum")
		delete(additionalProperties, "bindings")
		delete(additionalProperties, "filterCriteria")
		delete(additionalProperties, "hideAssertionsOlderThanNHours")
		delete(additionalProperties, "alertCategories")
		delete(additionalProperties, "query")
		delete(additionalProperties, "currentWBEntityCount")
		delete(additionalProperties, "hideAssertionsPresentMoreThanPercentageOfTime")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableAssertionSearchRequestDto struct {
	value *AssertionSearchRequestDto
	isSet bool
}

func (v NullableAssertionSearchRequestDto) Get() *AssertionSearchRequestDto {
	return v.value
}

func (v *NullableAssertionSearchRequestDto) Set(val *AssertionSearchRequestDto) {
	v.value = val
	v.isSet = true
}

func (v NullableAssertionSearchRequestDto) IsSet() bool {
	return v.isSet
}

func (v *NullableAssertionSearchRequestDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAssertionSearchRequestDto(val *AssertionSearchRequestDto) *NullableAssertionSearchRequestDto {
	return &NullableAssertionSearchRequestDto{value: val, isSet: true}
}

func (v NullableAssertionSearchRequestDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAssertionSearchRequestDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
