/*
Asserts, Inc

Asserts Public API

API version: 2025.11.24-113232
Contact: support@asserts.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gcom

import (
	"encoding/json"
)

// checks if the AssertionSourceMetricRequestDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AssertionSourceMetricRequestDto{}

// AssertionSourceMetricRequestDto struct for AssertionSourceMetricRequestDto
type AssertionSourceMetricRequestDto struct {
	StartTime            *int64            `json:"startTime,omitempty"`
	EndTime              *int64            `json:"endTime,omitempty"`
	Labels               map[string]string `json:"labels,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _AssertionSourceMetricRequestDto AssertionSourceMetricRequestDto

// NewAssertionSourceMetricRequestDto instantiates a new AssertionSourceMetricRequestDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAssertionSourceMetricRequestDto() *AssertionSourceMetricRequestDto {
	this := AssertionSourceMetricRequestDto{}
	return &this
}

// NewAssertionSourceMetricRequestDtoWithDefaults instantiates a new AssertionSourceMetricRequestDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAssertionSourceMetricRequestDtoWithDefaults() *AssertionSourceMetricRequestDto {
	this := AssertionSourceMetricRequestDto{}
	return &this
}

// GetStartTime returns the StartTime field value if set, zero value otherwise.
func (o *AssertionSourceMetricRequestDto) GetStartTime() int64 {
	if o == nil || IsNil(o.StartTime) {
		var ret int64
		return ret
	}
	return *o.StartTime
}

// GetStartTimeOk returns a tuple with the StartTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssertionSourceMetricRequestDto) GetStartTimeOk() (*int64, bool) {
	if o == nil || IsNil(o.StartTime) {
		return nil, false
	}
	return o.StartTime, true
}

// HasStartTime returns a boolean if a field has been set.
func (o *AssertionSourceMetricRequestDto) HasStartTime() bool {
	if o != nil && !IsNil(o.StartTime) {
		return true
	}

	return false
}

// SetStartTime gets a reference to the given int64 and assigns it to the StartTime field.
func (o *AssertionSourceMetricRequestDto) SetStartTime(v int64) {
	o.StartTime = &v
}

// GetEndTime returns the EndTime field value if set, zero value otherwise.
func (o *AssertionSourceMetricRequestDto) GetEndTime() int64 {
	if o == nil || IsNil(o.EndTime) {
		var ret int64
		return ret
	}
	return *o.EndTime
}

// GetEndTimeOk returns a tuple with the EndTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssertionSourceMetricRequestDto) GetEndTimeOk() (*int64, bool) {
	if o == nil || IsNil(o.EndTime) {
		return nil, false
	}
	return o.EndTime, true
}

// HasEndTime returns a boolean if a field has been set.
func (o *AssertionSourceMetricRequestDto) HasEndTime() bool {
	if o != nil && !IsNil(o.EndTime) {
		return true
	}

	return false
}

// SetEndTime gets a reference to the given int64 and assigns it to the EndTime field.
func (o *AssertionSourceMetricRequestDto) SetEndTime(v int64) {
	o.EndTime = &v
}

// GetLabels returns the Labels field value if set, zero value otherwise.
func (o *AssertionSourceMetricRequestDto) GetLabels() map[string]string {
	if o == nil || IsNil(o.Labels) {
		var ret map[string]string
		return ret
	}
	return o.Labels
}

// GetLabelsOk returns a tuple with the Labels field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssertionSourceMetricRequestDto) GetLabelsOk() (map[string]string, bool) {
	if o == nil || IsNil(o.Labels) {
		return map[string]string{}, false
	}
	return o.Labels, true
}

// HasLabels returns a boolean if a field has been set.
func (o *AssertionSourceMetricRequestDto) HasLabels() bool {
	if o != nil && !IsNil(o.Labels) {
		return true
	}

	return false
}

// SetLabels gets a reference to the given map[string]string and assigns it to the Labels field.
func (o *AssertionSourceMetricRequestDto) SetLabels(v map[string]string) {
	o.Labels = v
}

func (o AssertionSourceMetricRequestDto) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AssertionSourceMetricRequestDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.StartTime) {
		toSerialize["startTime"] = o.StartTime
	}
	if !IsNil(o.EndTime) {
		toSerialize["endTime"] = o.EndTime
	}
	if !IsNil(o.Labels) {
		toSerialize["labels"] = o.Labels
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *AssertionSourceMetricRequestDto) UnmarshalJSON(data []byte) (err error) {
	varAssertionSourceMetricRequestDto := _AssertionSourceMetricRequestDto{}

	err = json.Unmarshal(data, &varAssertionSourceMetricRequestDto)

	if err != nil {
		return err
	}

	*o = AssertionSourceMetricRequestDto(varAssertionSourceMetricRequestDto)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "startTime")
		delete(additionalProperties, "endTime")
		delete(additionalProperties, "labels")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableAssertionSourceMetricRequestDto struct {
	value *AssertionSourceMetricRequestDto
	isSet bool
}

func (v NullableAssertionSourceMetricRequestDto) Get() *AssertionSourceMetricRequestDto {
	return v.value
}

func (v *NullableAssertionSourceMetricRequestDto) Set(val *AssertionSourceMetricRequestDto) {
	v.value = val
	v.isSet = true
}

func (v NullableAssertionSourceMetricRequestDto) IsSet() bool {
	return v.isSet
}

func (v *NullableAssertionSourceMetricRequestDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAssertionSourceMetricRequestDto(val *AssertionSourceMetricRequestDto) *NullableAssertionSourceMetricRequestDto {
	return &NullableAssertionSourceMetricRequestDto{value: val, isSet: true}
}

func (v NullableAssertionSourceMetricRequestDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAssertionSourceMetricRequestDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
