// @generated by protoc-gen-connect-query v1.4.2 with parameter "target=ts"
// @generated from file vcs/v1/vcs.proto (package vcs.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { MethodKind } from "@bufbuild/protobuf";
import { GetCommitRequest, GetCommitResponse, GetCommitsRequest, GetCommitsResponse, GetFileRequest, GetFileResponse, GithubAppRequest, GithubAppResponse, GithubLoginRequest, GithubLoginResponse, GithubRefreshRequest, GithubRefreshResponse } from "./vcs_pb.js";

/**
 * @generated from rpc vcs.v1.VCSService.GithubApp
 */
export const githubApp = {
  localName: "githubApp",
  name: "GithubApp",
  kind: MethodKind.Unary,
  I: GithubAppRequest,
  O: GithubAppResponse,
  service: {
    typeName: "vcs.v1.VCSService"
  }
} as const;

/**
 * @generated from rpc vcs.v1.VCSService.GithubLogin
 */
export const githubLogin = {
  localName: "githubLogin",
  name: "GithubLogin",
  kind: MethodKind.Unary,
  I: GithubLoginRequest,
  O: GithubLoginResponse,
  service: {
    typeName: "vcs.v1.VCSService"
  }
} as const;

/**
 * @generated from rpc vcs.v1.VCSService.GithubRefresh
 */
export const githubRefresh = {
  localName: "githubRefresh",
  name: "GithubRefresh",
  kind: MethodKind.Unary,
  I: GithubRefreshRequest,
  O: GithubRefreshResponse,
  service: {
    typeName: "vcs.v1.VCSService"
  }
} as const;

/**
 * @generated from rpc vcs.v1.VCSService.GetFile
 */
export const getFile = {
  localName: "getFile",
  name: "GetFile",
  kind: MethodKind.Unary,
  I: GetFileRequest,
  O: GetFileResponse,
  service: {
    typeName: "vcs.v1.VCSService"
  }
} as const;

/**
 * @generated from rpc vcs.v1.VCSService.GetCommit
 */
export const getCommit = {
  localName: "getCommit",
  name: "GetCommit",
  kind: MethodKind.Unary,
  I: GetCommitRequest,
  O: GetCommitResponse,
  service: {
    typeName: "vcs.v1.VCSService"
  }
} as const;

/**
 * @generated from rpc vcs.v1.VCSService.GetCommits
 */
export const getCommits = {
  localName: "getCommits",
  name: "GetCommits",
  kind: MethodKind.Unary,
  I: GetCommitsRequest,
  O: GetCommitsResponse,
  service: {
    typeName: "vcs.v1.VCSService"
  }
} as const;
