name: Action Stats
description: Upload GitHub Action telemetry data to an OTLP endpoint
author: Pete Wall

branding:
  icon: upload-cloud
  color: orange

runs:
  using: docker
  image: docker://ghcr.io/grafana/hackathon-12-action-stat
  env:
    GH_TOKEN: '${{ inputs.github-token }}'
    TELEMETRY_URL: '${{ inputs.telemetry-url }}'
    TELEMETRY_USERNAME: '${{ inputs.telemetry-username }}'
    TELEMETRY_PASSWORD: '${{ inputs.telemetry-password }}'
    WORKFLOW_RUN_ID: '${{ inputs.workflow-run-id }}'
    UPLOAD_TIMEOUT: '${{ inputs.upload-timeout }}'
inputs:
  github-token:
    description: GitHub token for API access
    required: true
  telemetry-url:
    description: Telemetry URL
    required: true
  telemetry-username:
    description: Telemetry username
    required: true
  telemetry-password:
    description: Telemetry password
    required: true
  workflow-run-id:
    description: Workflow run ID
    required: true
  upload-timeout:
    description: Upload timeout
    required: false
    default: '300'
