apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  annotations:
    tanka.dev/namespaced: "false"
  labels:
    crossplane.io/xrd: xaccesspolicytokens.cloud.grafana.net.namespaced
  name: accesspolicytoken-namespaced
spec:
  compositeTypeRef:
    apiVersion: cloud.grafana.net.namespaced/v1alpha1
    kind: XAccessPolicyToken
  mode: Pipeline
  pipeline:
    - functionRef:
        name: function-patch-and-transform
      input:
        apiVersion: pt.fn.crossplane.io/v1beta1
        kind: Resources
        resources:
          - base:
              apiVersion: cloud.grafana.crossplane.io/v1alpha1
              kind: AccessPolicyToken
            name: accesspolicytoken
            patches:
              - fromFieldPath: spec.parameters.externalName
                toFieldPath: "metadata.annotations[\"crossplane.io/external-name\"]"
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.selectorLabel
                toFieldPath: "metadata.labels[\"selector\"]"
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.deletionPolicy
                toFieldPath: spec.deletionPolicy
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.forProvider.accessPolicyId
                toFieldPath: spec.forProvider.accessPolicyId
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.forProvider.accessPolicyRef.name
                toFieldPath: spec.forProvider.accessPolicyRef.name
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.forProvider.accessPolicyRef.policy.resolution
                toFieldPath: spec.forProvider.accessPolicyRef.policy.resolution
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.forProvider.accessPolicyRef.policy.resolve
                toFieldPath: spec.forProvider.accessPolicyRef.policy.resolve
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.forProvider.accessPolicySelector.matchControllerRef
                toFieldPath: spec.forProvider.accessPolicySelector.matchControllerRef
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.forProvider.accessPolicySelector.matchLabels
                toFieldPath: spec.forProvider.accessPolicySelector.matchLabels
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.forProvider.accessPolicySelector.policy.resolution
                toFieldPath: spec.forProvider.accessPolicySelector.policy.resolution
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.forProvider.accessPolicySelector.policy.resolve
                toFieldPath: spec.forProvider.accessPolicySelector.policy.resolve
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.forProvider.displayName
                toFieldPath: spec.forProvider.displayName
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.forProvider.expiresAt
                toFieldPath: spec.forProvider.expiresAt
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.forProvider.name
                toFieldPath: spec.forProvider.name
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.forProvider.region
                toFieldPath: spec.forProvider.region
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.initProvider.accessPolicyId
                toFieldPath: spec.initProvider.accessPolicyId
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.initProvider.accessPolicyRef.name
                toFieldPath: spec.initProvider.accessPolicyRef.name
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.initProvider.accessPolicyRef.policy.resolution
                toFieldPath: spec.initProvider.accessPolicyRef.policy.resolution
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.initProvider.accessPolicyRef.policy.resolve
                toFieldPath: spec.initProvider.accessPolicyRef.policy.resolve
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.initProvider.accessPolicySelector.matchControllerRef
                toFieldPath: spec.initProvider.accessPolicySelector.matchControllerRef
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.initProvider.accessPolicySelector.matchLabels
                toFieldPath: spec.initProvider.accessPolicySelector.matchLabels
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.initProvider.accessPolicySelector.policy.resolution
                toFieldPath: spec.initProvider.accessPolicySelector.policy.resolution
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.initProvider.accessPolicySelector.policy.resolve
                toFieldPath: spec.initProvider.accessPolicySelector.policy.resolve
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.initProvider.displayName
                toFieldPath: spec.initProvider.displayName
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.initProvider.expiresAt
                toFieldPath: spec.initProvider.expiresAt
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.initProvider.name
                toFieldPath: spec.initProvider.name
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.initProvider.region
                toFieldPath: spec.initProvider.region
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.managementPolicies
                toFieldPath: spec.managementPolicies
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.providerConfigRef.name
                toFieldPath: spec.providerConfigRef.name
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.providerConfigRef.policy.resolution
                toFieldPath: spec.providerConfigRef.policy.resolution
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.providerConfigRef.policy.resolve
                toFieldPath: spec.providerConfigRef.policy.resolve
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.publishConnectionDetailsTo.configRef.name
                toFieldPath: spec.publishConnectionDetailsTo.configRef.name
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.publishConnectionDetailsTo.configRef.policy.resolution
                toFieldPath: spec.publishConnectionDetailsTo.configRef.policy.resolution
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.publishConnectionDetailsTo.configRef.policy.resolve
                toFieldPath: spec.publishConnectionDetailsTo.configRef.policy.resolve
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.publishConnectionDetailsTo.metadata.annotations
                toFieldPath: spec.publishConnectionDetailsTo.metadata.annotations
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.publishConnectionDetailsTo.metadata.labels
                toFieldPath: spec.publishConnectionDetailsTo.metadata.labels
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.publishConnectionDetailsTo.metadata.type
                toFieldPath: spec.publishConnectionDetailsTo.metadata.type
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.publishConnectionDetailsTo.name
                toFieldPath: spec.publishConnectionDetailsTo.name
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.writeConnectionSecretToRef.name
                toFieldPath: spec.writeConnectionSecretToRef.name
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.writeConnectionSecretToRef.namespace
                toFieldPath: spec.writeConnectionSecretToRef.namespace
                type: FromCompositeFieldPath
      step: patch-and-transform