receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "localhost:4317"
      http:
        endpoint: "localhost:4318"
  telemetryapi:

exporters:
  otlphttp/grafana_cloud:
    # https://github.com/open-telemetry/opentelemetry-collector/tree/main/exporter/otlphttpexporter
    endpoint: "${env:GRAFANA_CLOUD_OTLP_ENDPOINT}"
    auth:
      authenticator: basicauth/grafana_cloud

extensions:
  basicauth/grafana_cloud:
    # https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/extension/basicauthextension
    client_auth:
      username: "${env:GRAFANA_CLOUD_INSTANCE_ID}"
      password: "${env:GRAFANA_CLOUD_API_KEY:-${secretsmanager:${env:GRAFANA_CLOUD_API_KEY_ARN}}}"

processors:
  batch:
  decouple:

service:
  extensions: [basicauth/grafana_cloud]
  pipelines:
    traces:
      receivers: [telemetryapi,otlp]
      processors: [batch,decouple]
      exporters: [otlphttp/grafana_cloud]
    logs:
      receivers: [telemetryapi,otlp]
      processors: [batch,decouple]
      exporters: [otlphttp/grafana_cloud]
    metrics:
      receivers: [otlp]
      processors: [batch,decouple]
      exporters: [otlphttp/grafana_cloud]
