/**
 * Automatically generated by @grafana/openapi-to-k6: 0.3.2
 * Do not edit manually.
 * Simple API
 * An API with a single GET request that takes a path parameter
 * Service version: 1.0.0
 */
export type GetItemById200 = {
  id?: string
  name?: string
  description?: string
}
