/*
Asserts, Inc

Testing DrilldownConfigMigrationControllerAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package gcom

import (
	"context"
	"testing"

	openapiclient "github.com/grafana/grafana-asserts-public-clients/go/gcom"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func Test_gcom_DrilldownConfigMigrationControllerAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test DrilldownConfigMigrationControllerAPIService MigrateConfigs", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		httpRes, err := apiClient.DrilldownConfigMigrationControllerAPI.MigrateConfigs(context.Background()).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
