// @generated by protoc-gen-connect-query v1.4.2 with parameter "target=ts"
// @generated from file adhocprofiles/v1/adhocprofiles.proto (package adhocprofiles.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { MethodKind } from "@bufbuild/protobuf";
import { AdHocProfilesGetRequest, AdHocProfilesGetResponse, AdHocProfilesListRequest, AdHocProfilesListResponse, AdHocProfilesUploadRequest } from "./adhocprofiles_pb.js";

/**
 * Upload a profile to the underlying store. The request contains a name and a base64 encoded pprof file. The response
 * contains a generated unique identifier, a flamegraph and a list of found sample types within the profile.
 *
 * @generated from rpc adhocprofiles.v1.AdHocProfileService.Upload
 */
export const upload = {
  localName: "upload",
  name: "Upload",
  kind: MethodKind.Unary,
  I: AdHocProfilesUploadRequest,
  O: AdHocProfilesGetResponse,
  service: {
    typeName: "adhocprofiles.v1.AdHocProfileService"
  }
} as const;

/**
 * Retrieves a profile from the underlying store by id and an optional sample type. The response is similar to the one
 * for the upload method.
 *
 * @generated from rpc adhocprofiles.v1.AdHocProfileService.Get
 */
export const get = {
  localName: "get",
  name: "Get",
  kind: MethodKind.Unary,
  I: AdHocProfilesGetRequest,
  O: AdHocProfilesGetResponse,
  service: {
    typeName: "adhocprofiles.v1.AdHocProfileService"
  }
} as const;

/**
 * Retrieves a list of profiles found in the underlying store.
 *
 * @generated from rpc adhocprofiles.v1.AdHocProfileService.List
 */
export const list = {
  localName: "list",
  name: "List",
  kind: MethodKind.Unary,
  I: AdHocProfilesListRequest,
  O: AdHocProfilesListResponse,
  service: {
    typeName: "adhocprofiles.v1.AdHocProfileService"
  }
} as const;
