{
 "title": "Snyk Exporter",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "project",
    "label": "Project",
    "query": {
     "query": "query_result(topk(10, sort_desc(sum(snyk_vulnerabilities_total) by (project))))"
    }
   }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total vulnerabilities per project",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(snyk_vulnerabilities_total{project=~\"$project\"}) by (project)"
    }
   ]
  },
  {
   "title": "$project",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "repeat": "project",
   "targets": [
    {}
   ]
  },
  {
   "title": "Issue count",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 16, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(severity) (snyk_vulnerabilities_total{project=~\"$project\"})",
     "legendFormat": "{{severity}}"
    }
   ]
  },
  {
   "title": "Critical",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(snyk_vulnerabilities_total{severity=\"critical\", project=~\"$project\"})"
    }
   ]
  },
  {
   "title": "High",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(snyk_vulnerabilities_total{severity=\"high\", project=~\"$project\"})"
    }
   ]
  },
  {
   "title": "Medium",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(snyk_vulnerabilities_total{severity=\"medium\", project=~\"$project\"})"
    }
   ]
  },
  {
   "title": "Low",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(snyk_vulnerabilities_total{severity=\"low\", project=~\"$project\"})"
    }
   ]
  },
  {
   "title": "Issues by type",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 13 },
   "targets": [
    {
     "expr": "sum(snyk_vulnerabilities_total{project=~\"$project\"}) by (issue_title, severity)"
    }
   ]
  }
 ]
}