FROM golang:1.22.8-bookworm

RUN apt-get update && apt-get install -y --no-install-recommends ca-certificates && update-ca-certificates && \
    addgroup --system --gid 127 docker && adduser --uid 1001 --gid 127 --disabled-password runner

COPY k6dist /usr/bin/

USER runner

ENTRYPOINT ["k6dist"]
