apiVersion: 1
datasources:
- name: loki
  type: loki
  access: proxy
  url: http://loki:3100
  editable: true
  isDefault: true
  jsonData:
    derivedFields:
      - datasourceUid: "tempo"
        matcherRegex: "trace_id"
        matcherType: "label"
        name: "trace_id"
        targetBlank: true
        url: "$${__value.raw}"
        urlDisplayLabel: ""

- name: prometheus
  type: prometheus
  url: http://prometheus:9090
  editable: true
  jsonData:
    prometheusType: Prometheus
    prometheusVersion: "2.50.0"
    cacheLevel: 'None'
    timeInterval: 3s
    httpMethod: "POST"
    exemplarTraceIdDestinations:
      - datasourceUid: "tempo"
        name: "trace_id"

- name: tempo
  type: tempo
  url: "http://tempo:3200"
  editable: true
  jsonData:
    nodeGraph: 
      enabled: true
    serviceMap:
      datasourceUid: 'prometheus'
    tracesToLogsV2:
      datasourceUid: 'loki'
      filterBySpanID: false
    tracesToMetrics:
      datasourceUid: 'prometheus'