FROM asserts/otel-collector:v0.0.93

WORKDIR /opt/asserts
COPY start-collector.sh /opt/asserts

WORKDIR /etc/asserts
COPY config/collector-config-otlp.yaml /etc/asserts
COPY config/collector-config-otlphttp.yaml /etc/asserts
COPY config/collector-config-cloudtrace.yaml /etc/asserts
COPY config/collector-config-aws-xray.yaml /etc/asserts

EXPOSE 8888
EXPOSE 8889
EXPOSE 9465
EXPOSE 4317
EXPOSE 4318
EXPOSE 14278
EXPOSE 14250

ENTRYPOINT /opt/asserts/start-collector.sh