#!/usr/bin/env bash
#
# Generate protobuf bindings.

set -e
set -u

cd "$(git rev-parse --show-toplevel)/proto"

proto_count=$(find . -name '*.proto' | wc -l)

if test "${proto_count}" -eq 0 ; then
	echo "W: no proto files found, nothing to generate."
	exit 0
fi

# Find all proto files and generate code for them. Allow for the possibility of
# having more than one proto file per directory, but assume that there's a
# single output per directory.
#
# Try not to assume too much about the structure of the directories.
find . -name '*.proto' -print0 |
	xargs -r -0 -n1 dirname |
	while read -r protodir ; do
		# Format
		buf format --path "${protodir}" -w

		# Check that are no breaking changes
		if test -f "${protodir}/protodef.binpb" ; then
			buf breaking . --against "${protodir}/protodef.binpb"
		fi

		# Generate new code
		buf generate --path "${protodir}"

		# Capture the new data to validate future changes against
		buf build --output "${protodir}/protodef.binpb"
	done
